spring:
  application:
    name: qdlsSpring

  datasource:
    url: ${DB_CONNECTION}
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true