spring:
  application:
    name: qdlsSpring

  datasource:
    url: ${DB_CONNECTION}
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
    show-summary: summary